services:
  ordem-de-servico-bd:
    image: postgres:latest
    container_name: ordem-de-servico-bd
    environment:
      POSTGRES_USER: esi
      POSTGRES_PASSWORD: esi
      POSTGRES_DB: so
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ordem-de-servico-api:
    image: tomcat:11.0.4-jdk21-temurin
    container_name: ordem-de-servico-api
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://ordem-de-servico-bd:5432/so
      DB_USER: esi
      DB_PASSWORD: esi
    volumes:
      - ./target/MyOrdemServicoAPI-1.0.1.war:/usr/local/tomcat/webapps/ROOT.war
    depends_on:
      - ordem-de-servico-bd

volumes:
  postgres_data:
    driver: local
